[ADD] af_rest_appointment: #221 Upgraded code quality for af_rest_app…
vertelab/odoo-af pull request #242
Opened 2020-10-15 13:45 UTC by rupareliyahemangi145

…ointment.

2020-10-19 09:19 UTC, MickeHolm requested changes

2020-10-19 09:19 UTC, MickeHolm commented on af_rest_appointment/models/af_appointment.py
> +        client_id = self.env['ir.config_parameter'].sudo(
This is almost unreadable. could you loook into any other way of getting these lines to go through Travis?

2020-10-19 09:19 UTC, MickeHolm commented on af_rest_appointment/models/af_appointment.py
> +        client_id = self.env['ir.config_parameter'].sudo(
This is almost unreadable. could you loook into any other way of getting these lines to go through Travis?

2020-10-19 09:19 UTC, MickeHolm commented on af_rest_appointment/models/af_appointment.py
> +        client_id = self.env['ir.config_parameter'].sudo(
This is almost unreadable. could you loook into any other way of getting these lines to go through Travis?

2020-11-27 12:56 UTC, daerio approved these changes

2020-11-27 12:56 UTC, merged