[ADD] af_template_module: #221 Upgraded code quality for af_template_…
vertelab/odoo-af pull request #246
Opened 2020-10-15 14:06 UTC by rupareliyahemangi145

…module.

2020-10-19 09:16 UTC, MickeHolm requested changes

2020-10-19 09:16 UTC, MickeHolm commented on af_template_module/views/res_partner.xml
> +            <page name="internal_notes"
Keep old line and move the comment above this line

2020-10-19 09:16 UTC, MickeHolm commented on af_template_module/views/res_partner.xml
> +            <xpath expr="//field[@name='phone']/.."
Keep old line and move the comment above this line

2020-10-19 09:16 UTC, MickeHolm commented on af_template_module/views/res_partner.xml
> +                <field name="test_model_ids"
Keep old line and move the comment above this line

2020-10-19 09:16 UTC, MickeHolm commented on af_template_module/views/res_partner.xml
> +                <field name="test_model_ids"
Keep old line and move the comment above this line

2020-10-19 09:16 UTC, MickeHolm commented on af_template_module/views/res_partner.xml
> +        <field name="sequence"
Keep old line and move the comment above this line

2020-12-13 08:39 UTC, timforsstromAF approved these changes

2021-04-06 07:16 UTC, closed without merging