ipf_planning - AFC-1051: Integration Visa Arbetsmarknadspolitisk Plan…
vertelab/odoo-af pull request #265
Opened 2020-10-19 11:24 UTC by aldindrag

Visa Arbetsmarknadspolitisk Planering i Af CRM.

2020-10-19 14:04 UTC, MickeHolm requested changes

2020-10-19 14:04 UTC, MickeHolm commented on ipf_planning/static/src/js/planning.js
> +                console.log(result);
Please don't log to console.

2020-10-19 14:04 UTC, MickeHolm commented on ipf_planning/static/src/js/planning.js
> +            console.log(rows);
Please don't log to console.

2020-10-20 09:22 UTC, aldindrag reviewed
Logs removed.

2020-10-20 09:23 UTC, merged